name: Branch Check

on:
  push:
    branches-ignore:
      - "main" # Ignores pushes to the main branch

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setting up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@sundaeswap"
          cache: yarn

      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile --ignore-scripts

      # Build dist folders
      - name: Build
        run: yarn build

      # Run Tests
      - name: Run Tests
        run: yarn test
