name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setting up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@sundaeswap"
          cache: yarn

      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile --ignore-scripts

      # Run Tests
      - name: Run Tests
        run: yarn test

      # Git Identity
      - name: Git Identity
        run: |
          git config --global user.name '🤖github-actions🍦'
          git config --global user.email '🤖github-actions🍦@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Bump Versions
      - name: Bump versions
        run: yarn version:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create Release
      - name: Publish
        run: yarn publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  # Deploy Documentation
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build Documentation Site
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
